#!/usr/bin/env bash

ROOT="$(cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")" && pwd)"

# shellcheck disable=1091
source "${ROOT}/commands/help"
# shellcheck disable=1091
source "${ROOT}/commands/known"
# shellcheck disable=1091
source "${ROOT}/commands/install"

command="${1}"
shift

case "${command}" in
  i|install) easy_goer_install "${@}";;
  k|known)   easy_goer_known "${@}";;
  h|help|'') easy_goer_help "${@}";;
  *)         echo "${0}: unknown command: ${command}" >&2; echo >&2; easy_goer_help >&2; exit 1;;
esac
