#!/bin/bash

ROOT="$(cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")" && pwd)"

# shellcheck disable=SC1090
source "${ROOT}/commands/help"
# shellcheck disable=SC1090
source "${ROOT}/commands/known"
# shellcheck disable=SC1090
source "${ROOT}/commands/install"

command="${1}"
shift

case "${command}" in
  i|install)
    easy_goer_install "${@}";;
  k|known)
    easy_goer_known "${@}";;
  h|help)
    easy_goer_help "${@}";;
  *)
    easy_goer_help "${@}"; exit 1;;
esac
