#!/bin/bash

# Detect root if needed.
if [[ -z "${ROOT}" ]]; then
  ROOT="$(cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/.." && pwd)"
fi

# Load lib.
# shellcheck disable=1091
source "${ROOT}/util/detect"
# shellcheck disable=1091
source "${ROOT}/util/check_file"

# The command itself.
easy_goer_install() {
  # Parse options and arguments.
  local args=() os='' arch='' version='' dir='' parse='true' pkg_dir='' url_file='' url='' checksum_file='' checksum='' basename=''

  while [[ -n "${1}" ]]; do
    if ${parse}; then
      case "${1}" in
        -a)  arch="${2}"; shift;;
        -a*) arch="${1:2}";;
        -o)  os="${2}"; shift;;
        -o*) os="${1:2}";;
        -u)  url="${2}"; shift;;
        -u*) url="${1:2}";;
        -s)  checksum="${2}"; shift;;
        -s*) checksum="${1:2}";;
        -h)  easy_goer_help; return 0;;
        --)  parse=false;;
        -*)  echo "go-easy install: invalid option: ${1}" >&2; echo >&2; easy_goer_help >&2; return 1;;
        *)   args+=("${1}");;
      esac
    else
      args+=("${1}")
    fi

    shift
  done

  # Check arguments count.
  if [[ ${#args[@]} != 2 ]]; then
    echo "go-easy install: wrong number of arguments (given ${#args[@]}, expected 2)" >&2
    return 1
  fi

  # Extract.
  version="${args[0]}"
  dir="${args[1]}"

  # If installation directory exists - refuse to do anything.
  if [[ -e "${dir}" ]]; then
    echo "go-easy install: ${dir} already exists - please remove it first" >&2
    return 1
  fi

  # Detect OS & architecture.
  easy_goer_detect
  os="${os:-${easy_goer_os}}"
  arch="${arch:-${easy_goer_arch}}"

  # Package dir.
  pkg_dir="${ROOT}/db/${version}/${os}/${arch}"

  # Get URL.
  if [[ -z "${url}" ]]; then
    url_file="${pkg_dir}/url"
    if [[ ! -f "${url_file}" ]]; then
      echo "go-easy install: unknown version: ${version}: file ${url_file} does not exist" >&2
      return 1
    fi

    url=$(< "${url_file}")
  fi

  # Get checksum.
  if [[ -z "${checksum}" ]]; then
    checksum_file="${pkg_dir}/checksum"
    if [[ ! -f "${checksum_file}" ]]; then
      echo "go-easy install: unknown version: ${version}: file ${checksum_file} does not exist" >&2
      return 1
    fi

    checksum=$(< "${checksum_file}")
  fi

  # Figure out basename.
  basename="${url##*/}"

  # Install time.
  mkdir -p "${ROOT}/tmp"
  cd "${ROOT}/tmp" || return 1

  # Check if file already exists and matches the checksum.
  if ! easy_goer_check_file "./${basename}" "${checksum}"; then
    # shellcheck disable=2154
    if [[ -z "${easy_goer_checksum}" ]]; then
      echo "go-easy install: file ${ROOT}/tmp/${basename} missing - downloading from ${url}" >&2
    else
      echo "go-easy install: file ${ROOT}/tmp/${basename} checksum mismatch" >&2
      echo "  expected: ${checksum}" >&2
      echo "    actual: ${easy_goer_checksum}" >&2
      echo "go-easy install: downloading from ${url}" >&2
      rm -rf "./${basename}"
    fi

    # Download and recheck.
    curl -SL "${url}" > "./${basename}"
    if ! easy_goer_check_file "./${basename}" "${checksum}"; then
      echo "go-easy install: file ${ROOT}/tmp/${basename} checksum mismatch" >&2
      echo "  expected: ${checksum}" >&2
      echo "    actual: ${easy_goer_checksum}" >&2
      echo "go-easy install: aborting" >&2
      return 1
    fi
  fi

  # Actual installation.
  mkdir -p "${dir}"
  tar xf "./${basename}" -C "${dir}" --strip-components=1
}

# If invoked directly, do the job.
if [[ "${BASH_SOURCE[0]}" = "${0}" ]]; then
  easy_goer_install "${@}"
fi
